#! /bin/bash

#    serenity - An automated episode renamer.
#    Copyright (C) 2010-2012  Florian Léger
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Launch script (self-contained version)

baseDir="$(dirname "$(readlink -f "${0}")")"

# Configuration file(s)
readonly -a serenity_env_conf=("${baseDir}/serenity.conf")

# Library path
readonly serenity_env_lib="${baseDir}/lib"

# Cache path
readonly serenity_env_cache="${baseDir}/cache"

# Script name
readonly serenity_env_executable="${0}"

unset baseDir

# Load the main library, the cli library and call serenity.cli.main
if [ -f "${serenity_env_lib}/serenity.sh" ]; then
  . "${serenity_env_lib}/serenity.sh"
  . "${serenity_env_lib}/cli.sh"
  serenity: serenity.cli.main "${@}"
else
  echo "ERROR: can't find ${serenity_env_lib}/serenity.sh. Aborting." >&2
  exit 1
fi
